### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by sunamiao** [JakobRat/RALF#3]
Hello, is this project running on Windows?

**Comment by JakobRat** [comment]
Hello, unfortunately, this project runs only on Linux. The easiest way to get started is to use the [IIC-OSIC-TOOLS](https://github.com/iic-jku/IIC-OSIC-TOOLS) docker container and install the requirements in a virtual environment.

**Comment by sunamiao** [comment]
Dear Jakob

Thank you for your kindly advices. I've successfully run the project on IIC-OSCI-TOOLS. I'm really insterested in this excellent project. However, as a rookie in this field, I still have many confusion on detailed implementation methods in the code after read your conference paper. To find more theoretical explanation regarding this project, I was trying to fetch your thesis on JKU's thesis database. Unfortunately, it is still not available until March 2025. Is it convenient for you to send a copy of your thesis in advance?  I understand there maybe some confidential protocol in you uni or institute. Still many thanks if it is not possbile.

Regards.
Anton

Contact: sunamiao1202@gmail.com

**Comment by JakobRat** [comment]
I'm delighted you've successfully run the project using IIC-OSCI-TOOLS. Regarding the documentation, there is no additional open-source material available beyond what has been published. I appreciate your understanding and wish you continued success with your projects.
